### ISSUE TITLE
Problem with Godot-3.2 - 

### ISSUE THREAD

**Issue by atari83** [ChemicalInk/godot-arabic-text#1]
Hello, and thanks alot for this great addons :)
Well, I was using arabic-text addon on Godot-3.1 without any issue but when i upgraded on 3.2 i noticed that Godot complaining about:

"Invalid operands 'int' and 'int' in operator '<<'." on line 39 arabic-text/bidi/unicodedata.gd

which is:
index = index2[index<<SHIFT + code&(1<<SHIFT - 1)]

I didnt know what is the best workaround to fix this, so i reported to you. :)

**Comment by 3akev** [comment]
Thanks for reporting! I can reproduce the problem, and even though I'm not entirely certain what went wrong, it seems that simplifying that line of code fixed the problem. Check out the [latest commit](https://github.com/ChemicalInk/godot-arabic-text/commit/966806cfd69c7fd5d93a080bc54b3e4a29f51e56).
