### ISSUE TITLE
The plugin does not work correctly with harakata

### ISSUE THREAD

**Issue by kpk-i710** [ChemicalInk/godot-arabic-text#17]
A good plugin, but only if the text is without harakat like أنا ذهبت إلى ,

if you add harakata it looks unnatural  أَنَا ذَهَبْتُ إِلَى الْبَيْتِ spaces between letters in the same word.

<img width="281" alt="exemp" src="https://user-images.githubusercontent.com/47340012/189260803-2101e734-f139-45cd-b6c8-21adf938e788.png">

is there a solution for this?

**Comment by nightblade9** [comment]
Godot 4 is coming out pretty soon, and it implements a proper solution that includes support for Arabic, Persian, Urdu, etc. Maybe you can use that instead?

**Comment by kpk-i710** [comment]
> Godot 4 is coming out pretty soon, and it implements a proper solution that includes support for Arabic, Persian, Urdu, etc. Maybe you can use that instead?

yes, I decided to develop now on godot 4, while they will upload it as a test version to google play, I'll see how many bugs I catch
