### ISSUE TITLE
Multi-lines ALabel gets lines inverted vertically

### ISSUE THREAD

**Issue by HanouaJ** [ChemicalInk/godot-arabic-text#7]
As the title explains, whenever I try an ALabel that is composed of multiple lines these lines order get inverted when rendered, the first line becomes the last and so on.

**Comment by 3akev** [comment]
Fixed!

**Comment by HanouaJ** [comment]
Doesn't look like it is fixed to me, pulled the latest code and still facing the same issue. A part from pulling the latest code are there any extra steps that I should do ?

**Comment by 3akev** [comment]
Not that I know of. The latest commit is pending approval for the asset library, but the main branch works. See this specific test: [link](https://github.com/ChemicalInk/godot-arabic-text/blob/7307974b6bd05aee9181fd8c8f2678ae581fbe5a/test/unit/test_simple_arabic.gd#L33-L41)

Are you doing something differently? Can you provide an example input? Maybe I can whip out a new test case.

**Comment by nightblade9** [comment]
@HanouaJ can you provide some additional details - maybe a screenshot of your label in Godot or in-game?

**Comment by HanouaJ** [comment]
After looking at the test case, I get where the problem come from: in your case you are using explicit end of lines (which works in the same fashion when I try it), however what I am trying to do is using a paragraph without explicit line jumps (which seems to me the most common scenario) and with "Autowrap" enabled on the ALabel. Here is a test I did on the master branch, just replaced the "سلام" with the text "تحتل ويكيبيديا العربية المركز الـ15 من حيث أضخم الويكيبيديات حسب عدد المقالات، والمرتبة 10 من ناحية العمق متجاوزةً بذلك نسبة العمق في ويكيبيديا الفرنسية والألمانية والإسبانية وغيرها،[بحاجة لدقة أكثر] وتلقى نسبة 1.2% من حجم زوار ويكيبيديا حول العالم" :

![alabel-test1](https://user-images.githubusercontent.com/6314530/87283902-131eb580-c4f6-11ea-84d2-f0d4fc8990ee.png)

In-game :

![alabel-test2](https://user-images.githubusercontent.com/6314530/87284095-4a8d6200-c4f6-11ea-84b6-5469a5800521.png)

**Comment by nightblade9** [comment]
Hmm, that's interesting. It could be the auto-wrap. The other thing that sticks out, is that your example uses non-Arabic characters (numbers, `.`, and percentage sign). Right now, mixing Arabic and non-Arabic characters doesn't really work.

**Comment by HanouaJ** [comment]
I tried only Arabic letters and that didn't change anything, the lines are always inverted. The auto-wrap works perfectly with latin alphabet.

**Comment by 3akev** [comment]
Appears autowrap assumes LTR. Needs to be implemented with bidi in consideration. Unsure if in scope of project.

**Comment by 3akev** [comment]
@kameloov implemented autowrap in #9, it's merged with a test case. Could probably use more, but this is enough for now.
Dunno how well it plays with bidi, though.
