### ISSUE TITLE
Mixing arabic and English  issue

### ISSUE THREAD

**Issue by kameloov** [ChemicalInk/godot-arabic-text#8]
When mixing Arabic and English in the same text the text displays incorrectly
![Screenshot from 2020-09-20 10-57-47](https://user-images.githubusercontent.com/38273914/93707505-86185e00-fb2f-11ea-8d37-89d944092770.png)
The same issue happens when mixing Arabic text with numbers.

**Comment by nightblade9** [comment]
The recommended workflow at this time is to translate (or maybe transliterate) all English words into Arabic. Mixing just doesn't work well.

**Comment by kameloov** [comment]
I have fixed this issue and also implemented the autowrap support. Previously, if the text cannot fit in one line and wrap happens the lines appear reversed, I have implemented a fix, please review it.

**Comment by 3akev** [comment]
Fixed in #9
